### ISSUE TITLE
Error recovery uneffective in Clojure grammar

### ISSUE THREAD

**Issue by marijnh** [lezer-parser/lezer#30]
With the grammar at https://github.com/nextjournal/codemirror.next-clojure/commit/0978054362afa76551e88e63604f5f1fec9b1b5a , some kinds errors in the middle of the file cause anything after that to parse poorly, though the language is regular enough that it should be trivial to recover.

**Comment by mk** [comment]
Here's a small sample to illustrate the problem, given the following Clojure code:
```clojure
(def hello "docstring" :world)
(def defn (fn defn []))
(def hello "docstring" :world)
```
and using the grammar at https://github.com/nextjournal/lezer-clojure/commit/5df9d9e67ea3a95ca1818838388ebca117b3cb54 (this is a separate repo just for the grammar), I get the following result:
<img width="301" alt="CleanShot 2020-09-01 at 09 49 17@2x" src="https://user-images.githubusercontent.com/1187/91823031-eb67e600-ec38-11ea-8e5c-cdd34c52a4b4.png">

There's also a live demo of this at https://nextjournal.github.io/codemirror.next-clojure/.

Let us know if it would be helpful to provide anything else, thanks!

**Comment by marijnh** [comment]
The problem seems to have been that the parser got stuck in its end state (it went ahead and reduced the wrapper for `expression+`), from which it could not recover. I've added a kludge in e5689c4194320e3a where, when recovering from such a state, the parser can restart it back to the start state, which seems to help a lot with this (released in lezer 0.10.1). Let me know if you're still seeing failures like this.

**Comment by mk** [comment]
Thank you! It's a lot better with 10.0.2. 

We are still seeing a problem with very large files (beyond 6000 lines) that do not fully highlight. It does recover after I continue typing at the end of the doc and files this size are extremely rare so I don't consider it a problem in practice.

If you would like to still look into it, you can reproduce it with the following steps:

1. Go to https://raw.githubusercontent.com/clojure/clojure/master/src/clj/clojure/core.clj and copy all 7895 lines
2. Go to https://nextjournal.github.io/codemirror.next-clojure/ and paste it
3. Scroll to the bottom and see that not everything is highlighted
4. Add a character at the end of the doc and observe that highlighting recoveres

In my tests the place where the highlighting stopped isn't deterministic and occurs somewhere beyond the 6000 line mark.

**Comment by marijnh** [comment]
> We are still seeing a problem with very large files (beyond 6000 lines) that do not fully highlight.

That sounds more like a codemirror/next issue. Which version of that library are you using? Something like that was fixed in 0.10.0, I think.

**Comment by mk** [comment]
We are using 0.10.0:
https://github.com/nextjournal/codemirror.next-clojure/blob/9f901a5a4ed53d479950ee0418e7b6c3af48c6f1/package.json#L3

**Comment by mk** [comment]
Oh, I see you just released 0.11. Will give it a try and report back.

**Comment by marijnh** [comment]
I'm not seeing this in a ~10k line JavaScript file, but I haven't set up a Clojure editor yet to see if that behaves differently.

**Comment by mk** [comment]
I'm still seeing the issue after upgrading https://nextjournal.github.io/codemirror.next-clojure/ to 0.11.0. The reproduction from the [comment above](https://github.com/lezer-parser/lezer/issues/30#issuecomment-685811682) still applies. But like I've written above, I don't think it's an issue in practice for us.

**Comment by marijnh** [comment]
Right, I can reproduce this now. Upgrading to lezer 0.10.3 should fix it.

**Comment by mk** [comment]
I haven't experienced the issue since upgrading to 0.10.3, thank you!
